name: 'projet_trivial'
version: '1.0.0'
profile: 'trivial_tp'

model-paths: ['src/models']

models:
  projet_trivial:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: table

    mart:
      +materialized: table
      +schema: gold

