version: 2

sources:
  - name: silver
    tables:
      - name: responses
        meta:
          external_location: "read_parquet('data/silver/responses.parquet')"

      - name: questions
        meta:
          external_location: "read_parquet('data/silver/questions_clean.parquet')"
